### ISSUE TITLE
Revision ID not recognized: new issue for Raspberry Pi 4 

### ISSUE THREAD

**Issue by thereeesah** [jcane86/motor-hat#125]
Having troubles running the library with my Raspberry Pi 4. Getting this error:
```
Error: We dont recognize your revision (Revision        : b03112,b03112). Sorry! get in touch and let me know so I'll add it
```
Came across this closed issue which is similar to mine: https://github.com/jcane86/motor-hat/issues/123. It looks like the library might just need to include this revision? Thanks!

**Comment by jcane86** [comment]
ih @thereeesah thanks for reporting this.. I just published a new version of the dependency that was missing this revision.

If you unsinstall and reinstall motor-hat it should work now. Let me know if youre still having any issues.

Cheers!
